---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secrets
  namespace: dev
spec:
  encryptedData:
    jwt-expires-in: AgAfnpNnBeUirSlqjvqY3IdyoMCszanMfk0UTit5hd5ZjEkHC0vU8+/xZoDWVU2W5eNHHHx+Aqs0DObclZmrN2yxwLx9bcYMOJJIjgANGqc1PX72UktfNhyQiOGDmR6iQarhPn1ycr/G9wsCahxAQXc+yPZcGTGcub6bxttQM5HVnxMgd5/OjNpF3voT3+0FSDvb3IS6aGTGoF+Z/CjbWrd/yn7OLYvI89hXs7n3zlgMvt3FsoJIzdg8OW2Ni37gfQPF0mP5mpl0sCNQgvU0MiP68ph4iAvRXVsSR2mMbRsh+3F4zbGTszi2gZGa3AjCVttbNfmZHmPfrFizIWtXK3lXS84Wf4gelX+a4Fjl0nw4iZpjU6op9/exPnw4PHa5Y7YLIbo/Jqdy8DG48A7FCejgQoO2TE7oSfP5dUAVY+4YPygV/REyP+3XzMq148pry/aQrYuw4F0HHBVythUwPxSkoNU5oMl7kBAMld8MiBLhKNqpHSg9TvYovjM7nGtJEWkMVklqmeyuJAo5m1N1Kybg8+xMEdosOgY1gZ0Uz/UsMvf3XCirKKJoYdEuESaHlU3tJiO057xbrvPtl0x690YfQtBjo5FfjNeryUhdvB/Pq5f+H8M72fObDahaGEmHixQ8h9dsezGUKWl3s891LgBZWHfieGc5knQjum41eAk9TDKofTEI3/kveIRWvXoDubWLpxiY3Q==
    jwt-secret: AgAJsTVzpiXNuWPm0GPTbSCdHMJizTeH6/D45lmXBlxYqU6hSHrNH80uBzvjEDfbP10qJyNFjtyuy/oV0Z+caDqnrjyzo9mM1TNgjOJ0DTgHlPijJKB3P6mRr1G0NY0k/qCtFfK3cVO4n6Vc20iYZZpZcg8Tm9JQ5mJcn7+kcJeiGvbR6/7EkN0zUYXLzcxrgsxLggfS+4R5A7Lcqs4uVrIivO3fIpa8CHSR/PtT0WOHs12KMoNJp3rvmGb4O6K4oPyZaMlTlm0pf6p5VqYCfCMV8q3jnL0fs+pvmCPgQHgW12zSXLSz2iu1f7CNXAbrO1zoTZHu1txli/+bhcaBC62DHhIIE1nf2w9poCIocjh14YnBfZafjvj3aiNO4EYIimkTWUlh64jVBlYzPpqvEdUmaEEjQoSSRsslPDkfpAgvLrFtu/6v+40ALQNPV2OHIJdV1KUQNK1oIJP1rM3mfenObhQkXzGCXXCGu/vL0aJAWX6L/I7PJMsRd9UXMjkwpFk0XhYMPniUMwcnX6bA0Foe+kpvO45NdpyD5jTZHOdccboCF3uASHkO6sv83R40qNGNBIesYH4XqUJv+MWPe8F1ThhCGr+AIwWHUSYd5P2kmpPoMzr4G/+VcW3C+V6IjV43vJwUqJ/t5ZDV6m8BvXM4CCznOp4hv8aI9M4qM44ag2hABMYlbcwFz/NVilLyv631RG8Uy4yItNVdrX2gum2FoOBkzq00IiG8a8zEmc/Ru/dVEqFDzhRON7JLP7ROTvkVebjDQ78Ng4N7W2HtkTTe
  template:
    metadata:
      name: api-secrets
      namespace: dev
