---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secrets
  namespace: dev
spec:
  encryptedData:
    jwt-expires-in: AgCjsDYin1Sy3G53L097lDCl5XQss8mjzTHO6n73363tkc89TLj9lfZ+7YiyO6TaW5rw3pIqtfaVQ28Th8UjpV6xhfWo/rE5kcq1L4UJUX+KAeA9y6bHGaL1RoiYKNpFYE6jq9gACyrMPgQ/tY5xiDbrCKJEemK3mgTi9EZPA9fY1rz1NdR20dOIijrNpzH2uzzw1C3qJ+jaswXcqtBX/LXCbbRX1kX/CRfA16Y/WSX+eoaf9bBsrSu0M0XW2aK4JV4M6XqsPg+0cEBPYUA9NEVQ9rqqVaxAol/niqR1T/9WIeC7gFONbKG0AhH8teVj0pP7m1rgiCsj5b71c9EYVXNk2iWZB0dQ7vD1UOPy/JYhrVGDdxtb01mFXOhdsFHcdtmZlsRCcaz56fnP1mQsF16VfGcY/BA8AjDcxV18fgRDy2qlF5w5iu1GbKhxBWl8LSmQ0/44uMfX9ZiWCZN39pbq+vfCraHqIIoJ34Z49X7Cc3efqK0l8mSE9Vic5xou9tvuxS+qF4Zs3GGYURYj5jM1KPJb3xFrrxs7RFbbbsOAydK6iDP2jrKufuGyOEeCW+D4lCHrzGpX4qqn26vilAhXNYx3ygfn9tXH32zBbrTUhG5hQHHOdag/6JgehsCwDEz0wN6ddviJSGdG+P3Gw0k3bj/dsR2h7PcpnwnPttn/QZu01Um7L73uKLnhWd6ZU68aWKV8
    jwt-secret: AgCG53EVbsb+daiHTWmTwiFad/rPvEJCXYncOS7ZNtM8rYhbYwGbG4UsDh33GZEGrdJ+ClsgFeB4vNybtcBBjOc3lU/NF+q1feLkHanQ2A1LWz5DvUzNHqI0k8ROfzaAkk1bRshVjM7caruhXsoConeKShoODfMPC8W+uhYL9Q704joEYpNCp2WAugxpC/ldiy9al1B7S+CqTqidRLX2RWwU1eLrCj3ytQiHAfJV9uWCuvoMvhxnpeAO3139KQsr8DaEmAtakM+CbEPv+SrhcaJCoLS01CJbLuXGegaIMYANH6q+sSJA3MtMYlZqmAwy9QUGnm629xgrrjgm/OxYxpGoRi5fyV5CnyKsMQjg7fM8pkNoxQwGFNscG7ajmUprllNM9Y6TGfNm3a33o76jWNlMiTVRO9PLy+EnS5ssOnlzo9YeSK5cz7zkOLI2Cp6gecStyg2p0UqIgnjIWgPrl0DxWM3AdZYQgfuzTDWB4ov2IHC6mukuCEK5pAytz1mAvaUZMWbsgiveOGoFSpqrGYgScjAYvmrXy5sn6X5L10l266jpl1IbEud9Q2+KyPIMLmba1uxHOUWoyZS06JonkE90c5Ov3W5YdE3qVuQvcxGqWokdjV03LmksTY0BZ5Fi5ich92erPsdOyh7cBKQH/Lsmhe8hPhyD8IhAzz0kqdugltlgmunWi7XtVGemxBPlQbIxjy9h0WlaKT3BzpQ/73E/PUG3ezFBkGBY32Xof+k0BZBkle5gTgcCqdJSsZP98ZMEk3UIvtZhuRyVlUOAnmYA
  template:
    metadata:
      name: api-secrets
      namespace: dev
