---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: api-secrets
spec:
  encryptedData:
    jwt-expires-in: AgBf2G+a2/i5g+79Gn7j7jQ4n4rnSG/1Z8eQn6lsQ+XwUeEvYibO9lou9XhdFCbnlgxzZgoPrSWe9jl/D94JE22If1h/5h6i5Aprkh/vL+DIdBaRCSinVPhtc55guRs2ASgMYim567O4vQrcIkZulDL3O0LB8Si7Kq6UWbFVdQ6bUSC/S4DjXWgmcvrpGfqHze5FPjme1HLfDT5B6htIsALnSqtPXyHUVhhgRktEP9YZJSZ7jwvfK6XT2bTD2UgHaVcO/1SHX182nFgB8/9huAolL4tPSUzPXM+kCKymnx2ndA3RAeYQK0tRcbtl+srj5wwIoQN9r2ThHj2m7jOFXebQR691Lw5vXH9s8Kqy6hwHOkf/6lNE9W87KI5AUFXLSSD8ppTwjiAvldek860XllWtmxTjWpaLV+1Jic3cyAJyRPoEq1aGo44lqm8q6yT+MEOuEmgvNY1dJRq7zmp7yjm55I+E+H2/9YtCCRFgPhdEWyRCUQmeOw9lm9BzQwkuIUJ2qWPHanX35d1t8Z005g+1aOtZBUvBMTNRWJIVyc0ANPwHlU1J+RB+sG18Dc9tSWBT1NmJ7duenlCXp95flajHkSsF5tdYq3GLu4Q4jFDNIdT9lUTvHwGMW7TLsmmBej+F7JmBrL1ajIzmPA/n0hUH7eQKa0A7yQR8ILj5Cw/R1dvVUBE9jtraJoKEF+fCJgRYNw==
    jwt-secret: AgAfyg7kcxBF5DZN9JJO32XJMLSeyApPiUrKZ56ARQNWCOYqJSe7Gg71qROqSafsWVR9bO32owik9vJXcxk9n0OA603wjqmmqZftIdSWDgjJKzVf9r5/AJh3Y7NAd+xy4X7AjSZsENh4vDrciif9jt41Odo8RVlvBxendkYd1kNZSkOL8t1mA2eufMueou3Z5+iiWc5BOwmfAJdpjKONrgo4fPcLFRs8x8KIWKEzqk5sNIx4CA2fcwKNgFBkUmyrHB8lJkMRDvTnajkakwzfTnMMLP7jtJGUtTv/9XzIUycPfmihNU0cNp54/t5nToTnT2Vy4t+oK7Sg7NBnqRo8e9GcsN7vHKxrOpmWSFCZ6e2h7GPf21/M9dFCa6hzgETiLwMpt0X4UoUvanTLfLcDZITJNxw/u1MQHc3+lyB4mmdHkNbnQALRcYu+QjmrcB5lVY9qP5uJUB2NHAzvzP8uzSPCq0T6rk1XIP9JelUt2fWTttqdq8RN4e6OV2CnI36IVRogYSUKDXk9LH46NNDYKbDNUwNwtf4J4qvqknnxo+nezzReeQ+sPE80rDdcXAJXlIvmsl9dQX5gWzo1ypm+tkWjS5WALSe9locaHnW/CRjOLuq+06YsX6/BR+ZTksv1RIlLxXLbeHRsOnGuZ0E2N2QljNq9rQbha3wRHel/ZSXDUd+7oNHToTN1UBgc4qg2YYczXJsPiAKDSBUXKQ23Jnyi6Svtg+4QB3ECVVHdU/LJnxgrO+YfSJrtmwbL9cvha9e5w6yUARXx7WWormbESxbs
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: api-secrets
