---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: api-secrets
spec:
  encryptedData:
    jwt-expires-in: AgBioMeLnVhhXf0ajOssYyXinr+/zOAP5I1NWIhVNyvAZI0JomBjnxF7ljNGUuSLOKsGdDtAfdXEj/G1KhpX0gDw6L7VWQoF2pBPC31kxHUPs2H0CAN2dqj8G///Ay2xigrHHZaScvdf1KxifJz5w67KktcQ1Ks46xfcDbR/dSCx7bvZCt2V6g+evqJZjlBNxnqAgr9N/sM+BhZmhCoJsOdCf1p3AuEPZj2p590SZBPJKcFw/OGYYjqAEpKxv1724lQcsUyOp7MoMOGrD1AXv/x8THySIIIim87qpGU+H1q7OgNpAgOy1IgeAYrwyJuReY/kqxkWMwG8ntdx7qZufz5g8t8FNqwbvz4SiD4/bTPCva6alg8JJCo2x0lV3qVDw9t8oF7mVtDv1YmvrtSWGWjbpXlHRbik3BnRm/xtV3KYmr5NNyPuwax+kIzBWnRbT2l6lbF+4DlcUXQssveVFhGCIqYM961j0KMs7m+5PFVYm0zEHbCKsJ1TCqkUQ/7/nBfBfQHMQI8s8PmNrCge1fnduWpny28Poe4p4RvQ+MDvUUey1VAMHMM4Mop5fVIZdYKQI/ASuR9Waj0qHmRL1ilLTAUMMkN9kyiehJbHlSOGyABbcXTY8PF5GrylJjNfD2cv91KEIGRfDt9tVX0pZkY2+YA991DpXjqiLSFdQCPFoj3z2lIIK4E5fhMCx/9O2epYWVQUtw==
    jwt-secret: AgBaUk/BeSzMrJmxnnS0kRely9MppKIkFLWYwNmuN2o9m8E+qDg/FZqWHt5HnmdHANAbMmXwuyo/IXsfMsxcxJAeFakxqVDe5kEp0uIbTqQeGBt1OZvae2BbyDGwvfbqrvXVIOJqtP/pdel77KkWefo5kmNY8WkRNYCu7R8VCRcjMEuKGtVWhZouR2WjL3cHvbEuSZsuDTNTn/UhRGhwPnj4yEvagpV7yPfCt27n6Zv0H+ttftglud1Z+oPoSnjMEadfhiZaa9eU1Z4tyeACxBL1o993EHFHobpGA7fnD7cWUeiyYzXrvZNVZO6NkrKkYT68L1FJZ6ynLDAD8sRbUKbKdhS7lxfnCTKbbVgSZuy/2TS17VqLa4amvtSIKjw1+jC3FMRRtAO3hnaNXqRqzyWuoO7tS5qBqArfMruGpZ3NIIZ+IJ64bJDGoTfAA/7xpX5lAqh+PaBkKGhf7DHqyoUprDlVzz/STRucF1is4g/PKvDTfz7wOPTq0LmaO8XQ0mGozO94LeCiKb2bA56h4oguQ8aLjvZyJRSzLs6qOAdD1ZkLPh3m+pjxLRjN7wShEfsI29qEvMn6jAsjCTLUvqXv2gU/ZL9s93AwB9qCGu2N9vfymizylmjOUKvYCZl3wyWW/LKE/oFQtMGreG3DPBxK+8NRZ5IarvJVCOMIUhpCuxzvzZvNVmJXXLg/lAYwiOjJVMUTuJ63o3UFLLOO4JJ91xiPDt/0ZSHZpuSJiRDwqy6GbA0SSoTjWEiG581CEqqi7KsoHXSDiMAn5Ilo0Bm/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: api-secrets
