---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: api-secrets
spec:
  encryptedData:
    jwt-expires-in: AgCRWav4G1u0Gbw64DJ5jE3jQ/7aSs06wRL4SSo3FfzJKd31l1qwL9qViPNC0Pdxvlv4DhO+HFpOwH24w7hDWf9dLaCmHxUdp9VxGH09kjheMgesl1rHXR4k5ob94OMogiUPMpg0mWBubR65aNfK06jybreHhqpL1gezM9EN+gzpQi+gqJvzJz006eDfPVGPv9xIB6QUetOZ6EAVpF2r3kAM5Hav6H2crh5u+TgyFe372mZuB43snizmWIGnsRWaw8+mLDHAUK6FVo/UOz8Up/nRCaUx+PM3OPPX3LLZ0fEoGG3xuUKaUspht2hcrpiQSHT2fWCTGV0yWxPpFqF8UWb6NbSaprPa1I5QzKu/74ycrY40g7YhPeM8oH6zElZPUmCUItibjatNyDaM1uODQaKwB401z/6zh9H3yVBEZTEfs4BbCdWeZyMj6z2ijr0G3r2qVnWq0IBZoQQfvq4SphDXfc3lIS6doznUUHoNCtNAYAR3hhCLvZar37Hqvdj/hQw5Gy9jHx/uM4fqqTelmVMYpnn7/6PtEvE4dPHcdR7u39UQsKUAQ/3rTZe8lTm6nc3NhnGMHC/UQwLoGAe2XKTwexvlkD+clOx4/nGiCUqyAX5PVVx5HcjxiP3UdpUCa9vwG5cSwxddpv/FO0gQWvZyYK22/qU+BT1DAXJzXBr3oXh22a75VyAFFWugv/YPiTfr8g==
    jwt-secret: AgB8049z02eYT24Cg3ao5E0BQq2OoT1SAdTT7B/rHYWXhRLf7w8DFIlzL5c/gC9jF/ajEdS9agwfGcjgJcgcnb5V3x/Jk80Lnulvp2j43xG7m+u6BeJ7c+BEer05V8m5z8gV6ylnFXs+Jmoo08tFBu1knSiNqCGlhXuNnWIPCGdHtAyQsLaTtGGKo/tgTaWYlOmyNneG4KFlGAfkzpxjeHVaPluuDEx02KtTaGiJ6YczP7j48Pc0tdFqFe7HpYxF85XDpb3ZV41j1gVJFirU/e59+sq/GX/GCdU1oTAQpMHgaNMJAsIFd5WVLWtdnkPjMgerCRNhbFPk00GDiCg64Jrbt0CvZZlXVHFXgx4zV2xS29UJJu7H9rpRoD8jqwXyYejj/nyoHZ+MkWtZS+oGof5HG3Nes0kjBh3tlj1u0XHXKJCUDcgB5zi+vAE+xJNF31XOB2lNuTQrgY6j8a5WRBRce+6ZpGkFO5PXjiuH9/6e9G6N5YGgY4bRrC67/a5IHmhZD1yOmamTB+apaRZsfyLKf3PwlrzNpYJ39D6VgOlgyXM4Llx8jQCRNHAM2fz4n8ZuAmPDOsBS4sWhJGnO0Genpusle6QRDphOw9/xuFvfb1OhZg2P290avvwM4Ef9PzckfE+ZAybGOGNkcAp5zrPDDmcA5Z8JvA1UsppqS5znJWg/nM3tcmAlKKpbRb8S9tcgYiiTl4Z2WzwG7B/XVt5s46VHgxa4uu7prGtKKlvenDaefzrKH7BzVxMUo3D1z12/SNYFO5FB7C8BTst4Muk0
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: api-secrets
