---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../api
  - cluster.yaml
  - api-secrets.sealedsecret.yaml
patches:
  - path: migrate-init.patch.yaml
    target:
      kind: Deployment
      name: api
