apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argocd.cab.uadebate.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-tls
  namespace: argocd
spec:
  secretName: dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - dev.cab.uadebate.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-tls
  namespace: argocd
spec:
  secretName: prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - cab.uadebate.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: preview-tls
  namespace: argocd
spec:
  secretName: preview-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.cab.uadebate.com"
