---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA25t+Hkm62uLhlC7GzW7vyCcbXSRqTC5pBbxptfYtq+1rAnB2H48hIlFx4iAOpyjG9ID5pPRWkEVfCIxk3vXC/7xl/nXepaO0L0jfONAQlrQ75U1yD4XmUsvjw1C4EJ0xiSe9ryZkH3TzedhEJeNKJCibcq3To8gk+6FnrZiAFwGlR3La4/frERYRK4GekNq4YX3A2Sx7DLVw0lToTrOc3cY6ul0YUVfdvBlEB78VYIdJDQuBL533USxpEGMoqn+CiF2C4Hf+m+ZBjgeqOBI4eqV5JuyJ/kpXb9y0sOO8M3FY89ZtwardVVRYe5doK5ucl/cHeE2DAmCtsUbIz/yNlMx5pIHDG9QCMNF6z+GVwdbG/IXyqMsGCWqga2dzHGWMqb2ShVxzzyFC6+WC6c5A3F5vUGpQYwzuwxlJBVo4d5Trvz3ccOZMlzRorb6n7HbYSeQiJ58nL7F53lzni3sb4ka2+B5xLw6MNxwHr/HjfPHp8lkSOrgYNgGLgH3hcKZSYs4IWLvOpgNdlANJZ6tjmJdn7TWqcE/BBi9U8QRGZENbTjNJcAwx7l4jgljoWAUZKF5+EAw4fUT0Me8mj2TlJm14BRCogpt5mDJk2opurzn70mv9YeZ/P8pr2oxrdhUYU3SvBFoxv+zQBwh/9UCNmcy1y6XXE2oT5YH6vb/f5nD4aMdfxgtvQJz/uF/oFvyht8MeMYs+SUwZ41aLO5jDbyolTTJRNWjSHt/qH7ECPDok44EVsmrhqQIrAv63ZtKjT9mMrtQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
