---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: ghcr.io/ukrainian-debate-dev-community/opendebate-api
    newName: ghcr.io/ukrainian-debate-dev-community/opendebate-api
    newTag: sha-e2b9316
